version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      actions:
        update-types:
          - "major"
          - "minor"
          - "patch"
